/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeEnkiAgent {
  constructor(name?: string | undefined | null, systemPromptPreamble?: string | undefined | null, model?: string | undefined | null, maxIterations?: number | undefined | null, workspaceHome?: string | undefined | null)
  run(sessionId: string, userMessage: string): Promise<unknown>
}
